languageCode = "ja"
languageName = "日本語"
weight = 4
title = "北海北"

[params]
  displayName = "日本語"
  isoCode = "ja"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/blowfish_logo_transparent.png"
  description = "プログラミングのヒントや技術的な洞察を共有する個人ブログ。"
  copyright = "著作権？もちろん私のものです！:wink:  © 2024 マー・ジンハイ"

[author]
  name = "北海北"
  email = "jinhai.ma@icloud.com"
  image = "img/logo.jpg"
  headline = "技術愛好者およびクリエイター、プログラミングと開発の素晴らしさを共有"
  bio = "私はマー・ジンハイ、技術ブロガー兼開発者です。プログラミング、フロントエンド、およびバックエンド技術に情熱を持っており、ブログを通じて価値あるプログラミングのヒント、ツールの使用ガイド、およびプロジェクトの経験を共有することに専念しています。開発経験が豊富で、PythonとJavaScriptを使用したプロジェクト開発を得意としています。ここでは、C++、Android開発、Linux設定、およびAI展開に関する深い記事を見つけることができます。私の共有を通じて、より多くの人々が技術を習得し、実際の問題を解決できることを願っています。"
  links = [
    { email = "mailto:jinhai.ma@icloud.com" },
    { tiktok = "https://v.douyin.com/ir3DatCr/" },
    { github = "https://github.com/Beihai-North" },
  ]
